header:
  license:
    spdx-id: MPL-2.0

  paths-ignore:
    - "**/*.md"
    - "LICENSE"
    - ".github/**/*.*"
    - ".idea/**/*"
    - ".vscode/**/*"
    - "Dockerfile"
    - "Makefile"
    - "docs/**/*"
    - "hack/*"
    - "**/*.yaml"
    - "**/*.yml"
    - "**/*.toml"
    - "**/.*ignore"
    - "README"
    - "**/*.txt"
    - "pom.xml"
    - "build.gradle.kts"
    - "gradle.properties"
    - "gradle-wrapper.properties"
    - "gradlew"
    - "gradlew.bat"
    - "settings.gradle.kts"
    - ".release-please-manifest.json"
    - "release-please-config.json"

  comment: on-failure
