name: Tests

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  integration:
    name: Integration Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
      - run: go install github.com/wndhydrnt/saturn-bot@main
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Download protobuf files
        run: make proto
      - name: Install the SDK
        run: mvn install --batch-mode -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
      - name: Create integration test plugin
        run: |
          cd integration_test
          mvn package --batch-mode -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
      - name: Run integration tests
        run: make test_integration
  unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Download protobuf files
        run: make proto
      - name: Verify
        run: mvn verify --batch-mode -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
